### ISSUE TITLE
reporte practica

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/actividad-3-practica-architect-Rufino07#1]
[REPORTE ARCHITEC.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Rufino07/files/12554082/REPORTE.ARCHITEC.pdf)

**Comment by Irvingzr16** [comment]
Portada: 25
Procedimiento:  19 el procedimiento está bien, pero falta ser más preciso
Figuras: 12 faltaron figuras
Resultados y conclusiones: 19 Falto redactar en la parte de resultados
_Puntos Totales:75_

**Calificacion: 15/ 20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
